# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27015:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
