version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27015:27017"
    environment:
      MONGO_INITDB_DATABASE: monolith
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
